version: "3.8"
services:
  auth-service:
    image: "sovon9/auth-service"
    ports:
      - 9000:9000
    environment:
      - clientId=demo-client
      - clientSecret=demo-secret
    networks:
      - service-network

  uaa-resource-server:
    image: "sovon9/uaa-resource-server"
    ports:
      - 8081:8081
    environment:
      - spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://auth-service:9000/uaa/oauth2/jwks
    networks:
      - service-network

networks:
  service-network:
    driver: bridge